apiVersion: v1
kind: Pod
metadata:
  name: mypod
spec: 
  containers:
    - name: mycontainer
      image: mysql:9.4.0
      ports:
        - containerPort: 3306
      envFrom:
        - configMapRef:
            name: my-config
        - secretRef:
            name: db-secret-pod
      volumeMounts:
        - name: mydb-values
          mountPath: /var/lib/mysql
  volumes:
    - name: mydb-values
      configMap:
        name: my-config
    - name: secret-volume
      secret: 
        secretName: db-secret-pod



