apiVersion: v1
kind: Pod
metadata:
  name: mypod
spec: 
  containers:
    - name: mycontainer
      image: mysql:9.4.0
      ports:
        - container port: 3306
      envFrom:
        - configMapRef:
            name: config
        - secretRef :
            name: db-secret-pod
      volumeMounts:
        - name: mydb-values
          mountPath: /var/lib/mysql
  volumes:
    - configMap:
      name: my-config



